# Site settings
title: Emily DeVoll Design
email: emilydevollart@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Emily DeVoll's UI Design portfolio and personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emilydevoll.com" # the base hostname & protocol for your site
twitter_username: devollemily
github_username:  emilydevoll

# Build settings
markdown: kramdown
